## POST ##
POST http://localhost:5000/api/posts HTTP/1.1
Content-type: application/json

{
    "titulo": "Titulo de prueba",
    "resumen": "Resumen de prueba",
    "categoria": "Categoria de prueba",
    "descripcion": "Descripcion de prueba",
    "recursos": "Recursos de prueba",
    "imagen": "Image de prueba",
    "estado": "0"
}